org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.workers.max=1
org.gradle.configuration-cache=false
kotlin.incremental=false
